{{- if .Values.persistence.dockerStorage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helix-sandbox.fullname" . }}-docker
  labels:
    {{- include "helix-sandbox.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.dockerStorage.accessModes | nindent 4 }}
  {{- if .Values.persistence.dockerStorage.storageClassName }}
  storageClassName: {{ .Values.persistence.dockerStorage.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.dockerStorage.size }}
{{- end }}
---
{{- if .Values.persistence.hydraData.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helix-sandbox.fullname" . }}-hydra
  labels:
    {{- include "helix-sandbox.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.hydraData.accessModes | nindent 4 }}
  {{- if .Values.persistence.hydraData.storageClassName }}
  storageClassName: {{ .Values.persistence.hydraData.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.hydraData.size }}
{{- end }}
---
{{- if .Values.persistence.workspaceData.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "helix-sandbox.fullname" . }}-workspace
  labels:
    {{- include "helix-sandbox.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.persistence.workspaceData.accessModes | nindent 4 }}
  {{- if .Values.persistence.workspaceData.storageClassName }}
  storageClassName: {{ .Values.persistence.workspaceData.storageClassName | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.persistence.workspaceData.size }}
{{- end }}
