{{- if .Values.qdrant.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helix-controlplane.fullname" . }}-qdrant
  labels:
    {{- include "helix-controlplane.labels" . | nindent 4 }}
    app.kubernetes.io/component: qdrant
spec:
  type: ClusterIP
  ports:
    - port: 6334
      targetPort: 6334
      protocol: TCP
      name: grpc
    - port: 6333
      targetPort: 6333
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/component: qdrant
    {{- include "helix-controlplane.selectorLabels" . | nindent 4 }}
{{- end }}

