{{- if .Values.typesense.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helix-controlplane.fullname" . }}-typesense
  labels:
    app.kubernetes.io/component: typesense
    {{- include "helix-controlplane.labels" . | nindent 4 }}
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app.kubernetes.io/component: typesense
      {{- include "helix-controlplane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/component: typesense
        {{- include "helix-controlplane.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "helix-controlplane.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: typesense
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.typesense.image.repository | default "registry.helixml.tech/helix/typesense" }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8108
              protocol: TCP
          env:
            - name: TYPESENSE_DATA_DIR
              value: /data
            - name: TYPESENSE_API_KEY
              value: {{ .Values.typesense.apiKey }}
          {{- if .Values.typesense.persistence.enabled }}
          volumeMounts:
            - name: typesense-storage
              mountPath: /data
          {{- end }}
      {{- if .Values.typesense.persistence.enabled }}
      volumes:
      - name: typesense-storage
        persistentVolumeClaim:
          claimName: {{ include "helix-controlplane.fullname" . }}-typesense-pvc
      {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
