# A unique identifier for this host
uuid = "b2eefd9e-e23b-482a-8043-1e07cd58d65c"

# The name that will be displayed in Moonlight
hostname = "Wolf"
# The version of this config file
config_version = 6
# A list of paired clients that will be allowed to stream
paired_clients = []

######################
# Profiles: a list of different profiles, each with a list of apps
######################
# The default profile, this is what is going to be showed in Moonlight clients
[[profiles]]
id = "moonlight-profile-id"

[[profiles.apps]]
start_virtual_compositor = true
title = 'Wolf UI'
icon_png_path = "https://raw.githubusercontent.com/games-on-whales/wolf-ui/refs/heads/main/src/Icons/wolf_ui_icon.png"
video_producer_buffer_caps = 'video/x-raw(memory:CUDAMemory)'

[profiles.apps.runner]
base_create_json = '''{
      "HostConfig": {
        "IpcMode": "host",
        "CapAdd": ["NET_RAW", "MKNOD", "NET_ADMIN", "SYS_ADMIN", "SYS_NICE"],
        "Privileged": false,
        "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
      }
    }'''
devices = []
env = [
    'GOW_REQUIRED_DEVICES=/dev/input/event* /dev/dri/* /dev/nvidia*',
    'WOLF_SOCKET_PATH=/var/run/wolf/wolf.sock',
    'WOLF_UI_AUTOUPDATE=False',
    'LOGLEVEL=INFO'
]
image = 'ghcr.io/games-on-whales/wolf-ui:main'
mounts = [
    '/var/run/wolf/wolf.sock:/var/run/wolf/wolf.sock'
]
name = 'Wolf-UI'
ports = []
type = 'docker'

[[profiles.apps]]
title = "Test ball"
icon_png_path = "https://raw.githubusercontent.com/games-on-whales/wolf/refs/heads/wolf-ui/docs/images/test_ball_icon.png"
start_virtual_compositor = false
start_audio_server = false

[profiles.apps.runner]
type = "process"
run_cmd = "sh -c \"while :; do echo 'running...'; sleep 10; done\""

[profiles.apps.video]
source = """
videotestsrc pattern=ball flip=true is-live=true !
video/x-raw, framerate={fps}/1
\
"""

[profiles.apps.audio]
source = "audiotestsrc wave=ticks is-live=true"

# An example profile that will be shown in our Wolf UI
[[profiles]]
id = "user"
name = "User"

[[profiles.apps]]
title = "Firefox"
icon_png_path = "https://games-on-whales.github.io/wildlife/apps/firefox/assets/icon.png"
start_virtual_compositor = true

[profiles.apps.runner]
type = "docker"
name = "WolfFirefox"
image = "ghcr.io/games-on-whales/firefox:edge"
mounts = []
env = [
    "RUN_SWAY=1",
    "MOZ_ENABLE_WAYLAND=1",
    "GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*",
]
devices = []
ports = []
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "Privileged": false,
    "CapAdd": ["NET_RAW", "MKNOD", "NET_ADMIN"],
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
\
"""

[[profiles.apps]]
title = "RetroArch"
icon_png_path = "https://games-on-whales.github.io/wildlife/apps/retroarch/assets/icon.png"
start_virtual_compositor = true

[profiles.apps.runner]
type = "docker"
name = "WolfRetroarch"
image = "ghcr.io/games-on-whales/retroarch:edge"
mounts = []
env = [
    "RUN_SWAY=true",
    "GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*",
]
devices = []
ports = []
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "CapAdd": ["NET_RAW", "MKNOD", "NET_ADMIN", "SYS_ADMIN", "SYS_NICE"],
    "Privileged": false,
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
\
"""

[[profiles.apps]]
title = "Steam"
icon_png_path = "https://games-on-whales.github.io/wildlife/apps/steam/assets/icon.png"
start_virtual_compositor = true

[profiles.apps.runner]
type = "docker"
name = "WolfSteam"
image = "ghcr.io/games-on-whales/steam:edge"
mounts = []
env = [
    "PROTON_LOG=1",
    "RUN_SWAY=true",
    "GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*",
]
devices = []
ports = []
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "CapAdd": ["SYS_ADMIN", "SYS_NICE", "SYS_PTRACE", "NET_RAW", "MKNOD", "NET_ADMIN"],
    "SecurityOpt": ["seccomp=unconfined", "apparmor=unconfined"],
    "Ulimits": [{"Name":"nofile", "Hard":10240, "Soft":10240}],
    "Privileged": false,
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
\
"""

[[profiles.apps]]
title = "Pegasus"
icon_png_path = "https://games-on-whales.github.io/wildlife/apps/pegasus/assets/icon.png"
start_virtual_compositor = true

[profiles.apps.runner]
type = "docker"
name = "WolfPegasus"
image = "ghcr.io/games-on-whales/pegasus:edge"
mounts = []
env = [
    "RUN_SWAY=1",
    "GOW_REQUIRED_DEVICES=/dev/input/event* /dev/dri/* /dev/nvidia*",
]
devices = []
ports = []
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "CapAdd": ["NET_RAW", "MKNOD", "NET_ADMIN", "SYS_ADMIN", "SYS_NICE"],
    "Privileged": false,
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
\
"""

[[profiles.apps]]
title = "Lutris"
icon_png_path = "https://games-on-whales.github.io/wildlife/apps/lutris/assets/icon.png"
start_virtual_compositor = true

[profiles.apps.runner]
type = "docker"
name = "WolfLutris"
image = "ghcr.io/games-on-whales/lutris:edge"
mounts = ["lutris:/var/lutris/:rw"]
env = [
    "RUN_SWAY=1",
    "GOW_REQUIRED_DEVICES=/dev/input/event* /dev/dri/* /dev/nvidia* /var/lutris/",
]
devices = []
ports = []
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "CapAdd": ["NET_RAW", "MKNOD", "NET_ADMIN", "SYS_ADMIN", "SYS_NICE"],
    "Privileged": false,
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
\
"""

[[profiles.apps]]
title = "Prismlauncher"
icon_png_path = "https://games-on-whales.github.io/wildlife/apps/prismlauncher/assets/icon.png"
start_virtual_compositor = true

[profiles.apps.runner]
type = "docker"
name = "Prismlauncher"
image = "ghcr.io/games-on-whales/prismlauncher:edge"
mounts = []
env = [
    "RUN_SWAY=1",
    "GOW_REQUIRED_DEVICES=/dev/input/event* /dev/dri/* /dev/nvidia* /var/lutris/",
]
devices = []
ports = []
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "CapAdd": ["NET_RAW", "MKNOD", "NET_ADMIN", "SYS_ADMIN", "SYS_NICE"],
    "Privileged": false,
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
\
"""

[[profiles.apps]]
title = 'Desktop (xfce)'
icon_png_path = "https://games-on-whales.github.io/wildlife/apps/xfce/assets/icon.png"

[profiles.apps.runner]
type = 'docker'
name = 'WolfXFCE'
image = 'ghcr.io/games-on-whales/xfce:edge'
env = ['GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*']
devices = []
mounts = []
ports = []
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "Privileged": false,
    "CapAdd": ["SYS_ADMIN", "SYS_NICE", "SYS_PTRACE", "NET_RAW", "MKNOD", "NET_ADMIN"],
    "SecurityOpt": ["seccomp=unconfined", "apparmor=unconfined"],
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
\
"""

[[profiles.apps]]
title = "EmulationStation"
icon_png_path = "https://games-on-whales.github.io/wildlife/apps/es-de/assets/icon.png"

[profiles.apps.runner]
type = "docker"
name = "WolfES-DE"
image = "ghcr.io/games-on-whales/es-de:edge"
mounts = []
env = ["RUN_SWAY=1", "MOZ_ENABLE_WAYLAND=1", "GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*", ]
devices = []
ports = []
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "Privileged": false,
    "CapAdd": ["NET_RAW", "MKNOD", "NET_ADMIN"],
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
\
"""

[[profiles.apps]]
title = 'Kodi'
icon_png_path = "https://games-on-whales.github.io/wildlife/apps/kodi/assets/icon.png"

[profiles.apps.runner]
type = 'docker'
name = 'WolfKodi'
image = 'ghcr.io/games-on-whales/kodi:edge'
env = ['RUN_SWAY=true', 'GOW_REQUIRED_DEVICES=/dev/input/* /dev/dri/* /dev/nvidia*']
devices = []
mounts = []
ports = []
base_create_json = """
{
  "HostConfig": {
    "IpcMode": "host",
    "Privileged": false,
    "CapAdd": ["NET_RAW", "MKNOD", "NET_ADMIN"],
    "DeviceCgroupRules": ["c 13:* rmw", "c 244:* rmw"]
  }
}
\
"""


######################
# Gstreamer: Video/Audio encoding pipelines and streaming settings
[gstreamer]

[gstreamer.video]

default_source = 'interpipesrc name=interpipesrc_{}_video listen-to={session_id}_video is-live=true stream-sync=restart-ts max-bytes=0 max-buffers=1 leaky-type=downstream'
default_sink = """
rtpmoonlightpay_video name=moonlight_pay \
payload_size={payload_size} fec_percentage={fec_percentage} min_required_fec_packets={min_required_fec_packets} !
appsink sync=false name=wolf_udp_sink
"""

######################
# Default settings for the main encoders
# To avoid repetition between H264, HEVC and AV1 encoders
[gstreamer.video.defaults.nvcodec]
video_params = """
cudaupload !
cudaconvertscale add-borders=true !
video/x-raw(memory:CUDAMemory), width={width}, height={height}, \
chroma-site={color_range}, format=NV12, colorimetry={color_space}, pixel-aspect-ratio=1/1\
"""

video_params_zero_copy = """
cudaupload !
cudaconvertscale add-borders=true !
video/x-raw(memory:CUDAMemory),format=NV12, width={width}, height={height}, pixel-aspect-ratio=1/1
"""

[gstreamer.video.defaults.qsv]
video_params = """
videoconvertscale !
video/x-raw, chroma-site={color_range}, width={width}, height={height}, format=NV12,
colorimetry={color_space}, pixel-aspect-ratio=1/1\
"""

video_params_zero_copy = """
vapostproc add-borders=true !
video/x-raw(memory:VAMemory), format=NV12, width={width}, height={height}, pixel-aspect-ratio=1/1\
"""

[gstreamer.video.defaults.va]
video_params = """
vapostproc add-borders=true !
video/x-raw, chroma-site={color_range}, width={width}, height={height}, format=NV12,
colorimetry={color_space}, pixel-aspect-ratio=1/1\
"""

video_params_zero_copy = """
vapostproc add-borders=true !
video/x-raw(memory:VAMemory), format=NV12, width={width}, height={height}, pixel-aspect-ratio=1/1\
"""

######################
# HEVC encoders
# Order here matters: Wolf will try them in order and pick the first one that's not failing
###
[[gstreamer.video.hevc_encoders]]
plugin_name = "nvcodec"
check_elements = ["nvh265enc", "cudaconvertscale", "cudaupload"]
encoder_pipeline = """
nvh265enc gop-size=-1 bitrate={bitrate} aud=false rc-mode=cbr zerolatency=true preset=p1 tune=ultra-low-latency multi-pass=two-pass-quarter !
h265parse !
video/x-h265, profile=main, stream-format=byte-stream\
"""

[[gstreamer.video.hevc_encoders]]
plugin_name = "qsv"
check_elements = ["qsvh265enc", "vapostproc"]
encoder_pipeline = """
qsvh265enc b-frames=0 gop-size=15 idr-interval=1 ref-frames=1 bitrate={bitrate} rate-control=cbr low-latency=1 target-usage=6 !
h265parse !
video/x-h265, profile=main, stream-format=byte-stream\
"""

[[gstreamer.video.hevc_encoders]]
plugin_name = "va"
check_elements = ["vah265enc", "vapostproc"]
encoder_pipeline = """
vah265enc aud=false b-frames=0 ref-frames=1 num-slices={slices_per_frame} bitrate={bitrate} cpb-size={bitrate} key-int-max=1024 rate-control=cqp target-usage=6 !
h265parse !
video/x-h265, profile=main, stream-format=byte-stream\
"""

[[gstreamer.video.hevc_encoders]]
plugin_name = "va"
check_elements = ["vah265lpenc", "vapostproc"] # lp: (Low Power)
encoder_pipeline = """
vah265lpenc aud=false b-frames=0 ref-frames=1 num-slices={slices_per_frame} bitrate={bitrate} cpb-size={bitrate} key-int-max=1024 rate-control=cqp target-usage=6 !
h265parse !
video/x-h265, profile=main, stream-format=byte-stream\
"""

[[gstreamer.video.hevc_encoders]]
plugin_name = "x265" # SW Encoding
check_elements = ["x265enc"]
video_params = """
videoconvertscale !
videorate !
video/x-raw, width={width}, height={height}, framerate={fps}/1, format=I420,
chroma-site={color_range}, colorimetry={color_space}\
"""
video_params_zero_copy = """
videoconvertscale !
videorate !
video/x-raw, width={width}, height={height}, framerate={fps}/1, format=I420,
chroma-site={color_range}, colorimetry={color_space}\
"""
encoder_pipeline = """
x265enc tune=zerolatency speed-preset=superfast bitrate={bitrate}
option-string="info=0:keyint=-1:qp=28:repeat-headers=1:slices={slices_per_frame}:aud=0:annexb=1:log-level=3:open-gop=0:bframes=0:intra-refresh=0" !
video/x-h265, profile=main, stream-format=byte-stream\
"""


######################
# H264 encoders
# Order here matters: Wolf will try them in order and pick the first one that's not failing
###
[[gstreamer.video.h264_encoders]]
plugin_name = "nvcodec"
check_elements = ["nvh264enc", "cudaconvertscale", "cudaupload"]
encoder_pipeline = """
nvh264enc preset=low-latency-hq zerolatency=true gop-size=15 rc-mode=cbr-ld-hq bitrate={bitrate} aud=false !
h264parse !
video/x-h264, profile=main, stream-format=byte-stream\
"""

[[gstreamer.video.h264_encoders]]
plugin_name = "qsv"
check_elements = ["qsvh264enc", "vapostproc"]
encoder_pipeline = """
qsvh264enc b-frames=0 gop-size=15 idr-interval=1 ref-frames=1 bitrate={bitrate} rate-control=cbr target-usage=6  !
h264parse !
video/x-h264, profile=main, stream-format=byte-stream\
"""

[[gstreamer.video.h264_encoders]]
plugin_name = "va"
check_elements = ["vah264enc", "vapostproc"]
encoder_pipeline = """
vah264enc aud=false b-frames=0 ref-frames=1 num-slices={slices_per_frame} bitrate={bitrate} cpb-size={bitrate} key-int-max=1024 rate-control=cqp target-usage=6 !
h264parse !
video/x-h264, profile=main, stream-format=byte-stream\
"""

[[gstreamer.video.h264_encoders]]
plugin_name = "va"
check_elements = ["vah264lpenc", "vapostproc"] # lp: (Low Power)
encoder_pipeline = """
vah264lpenc aud=false b-frames=0 ref-frames=1 num-slices={slices_per_frame} bitrate={bitrate} cpb-size={bitrate} key-int-max=1024 rate-control=cqp target-usage=6 !
h264parse !
video/x-h264, profile=main, stream-format=byte-stream\
"""


[[gstreamer.video.h264_encoders]]
plugin_name = "x264" # SW Encoding
check_elements = ["x264enc"]
encoder_pipeline = """
x264enc pass=qual tune=zerolatency speed-preset=superfast b-adapt=false bframes=0 ref=1
sliced-threads=true threads={slices_per_frame} option-string="slices={slices_per_frame}:keyint=infinite:open-gop=0"
b-adapt=false bitrate={bitrate} aud=false !
video/x-h264, profile=high, stream-format=byte-stream\
"""

##############
# AV1 encoders
###
[[gstreamer.video.av1_encoders]]
plugin_name = "nvcodec"
check_elements = ["nvav1enc", "cudaconvertscale", "cudaupload"]
encoder_pipeline = """
nvav1enc gop-size=-1 bitrate={bitrate} rc-mode=cbr zerolatency=true preset=p1 tune=ultra-low-latency multi-pass=two-pass-quarter !
av1parse !
video/x-av1, stream-format=obu-stream, alignment=frame, profile=main\
"""

[[gstreamer.video.av1_encoders]]
plugin_name = "qsv"
check_elements = ["qsvav1enc", "vapostproc"]
encoder_pipeline = """
qsvav1enc gop-size=15 ref-frames=1 bitrate={bitrate} rate-control=cbr low-latency=1 target-usage=6 !
av1parse !
video/x-av1, stream-format=obu-stream, alignment=frame, profile=main\
"""

[[gstreamer.video.av1_encoders]]
plugin_name = "va"
check_elements = ["vaav1enc", "vapostproc"]
encoder_pipeline = """
vaav1enc ref-frames=1 bitrate={bitrate} cpb-size={bitrate} key-int-max=1024 rate-control=cqp target-usage=6 !
av1parse !
video/x-av1, stream-format=obu-stream, alignment=frame, profile=main\
"""

[[gstreamer.video.av1_encoders]]
plugin_name = "va"
check_elements = ["vaav1lpenc", "vapostproc"] # LP = Low Power
encoder_pipeline = """
vaav1lpenc ref-frames=1 bitrate={bitrate} cpb-size={bitrate} key-int-max=1024 rate-control=cqp target-usage=6 !
av1parse !
video/x-av1, stream-format=obu-stream, alignment=frame, profile=main\
"""

[[gstreamer.video.av1_encoders]]
plugin_name = "aom"
check_elements = ["av1enc"]
video_params = """
videoconvertscale !
videorate !
video/x-raw, width={width}, height={height}, framerate={fps}/1, format=I420,
chroma-site={color_range}, colorimetry={color_space}\
"""
video_params_zero_copy = """
videoconvertscale !
videorate !
video/x-raw, width={width}, height={height}, framerate={fps}/1, format=I420,
chroma-site={color_range}, colorimetry={color_space}\
"""
encoder_pipeline = """
av1enc usage-profile=realtime end-usage=vbr target-bitrate={bitrate} !
av1parse !
video/x-av1, stream-format=obu-stream, alignment=frame, profile=main\
"""

###########
# Audio
###
[gstreamer.audio]
default_source = """
interpipesrc name=interpipesrc_{}_audio listen-to={session_id}_audio is-live=true stream-sync=restart-ts max-bytes=0 max-buffers=3 block=false\
"""

default_audio_params = "queue max-size-buffers=3 leaky=downstream ! audiorate ! audioconvert"

default_opus_encoder = """
opusenc bitrate={bitrate} bitrate-type=cbr frame-size={packet_duration} bandwidth=fullband \
audio-type=restricted-lowdelay max-payload-size=1400\
"""

default_sink = """
rtpmoonlightpay_audio name=moonlight_pay packet_duration={packet_duration} encrypt={encrypt} \
aes_key="{aes_key}" aes_iv="{aes_iv}" !
appsink name=wolf_udp_sink\
"""