name: trivy container scan

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '45 10 * * 1'

permissions:
  contents: read

jobs:
  image_scan:
    strategy:
      matrix:
        image:
        - 'registry.helixml.tech/helix/controlplane:latest'
        - 'postgres:12.13-alpine'
        - 'quay.io/keycloak/keycloak:23.0'
        - 'registry.helixml.tech/helix/gptscript-runner:latest' 
        - 'apache/tika:2.9.2.1'
        - 'registry.helixml.tech/helix/typesense:latest'
        - 'ghcr.io/go-rod/rod:v0.115.0'
    permissions:
      contents: read # for actions/checkout to fetch code
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Pull container image
        run: docker pull ${{ matrix.image }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.29.0
        with:
          image-ref: ${{ matrix.image }}
          format: 'template'
          template: '@/contrib/sarif.tpl'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
